"use client";
import {useEffect,useState} from "react";
export default function Home(){
 const [accounts,setAccounts]=useState([]),[jobs,setJobs]=useState([]),[workers,setWorkers]=useState([]),[logs,setLogs]=useState([]),[ig,setIg]=useState(null),[username,setUsername]=useState(""),[accountId,setAccountId]=useState(""),[url,setUrl]=useState(""),[action,setAction]=useState("view"),[count,setCount]=useState(20),[loading,setLoading]=useState(false),[message,setMessage]=useState("");
 async function refresh(){const [a,j,w,l,i]=await Promise.all([fetch("/api/accounts").then(r=>r.json()),fetch("/api/jobs").then(r=>r.json()),fetch("/api/workers").then(r=>r.json()),fetch("/api/logs").then(r=>r.json()),fetch("/api/instagram").then(r=>r.json())]);setAccounts(a.accounts||[]);setJobs(j.jobs||[]);setWorkers(w.workers||[]);setLogs(l.logs||[]);setIg(i.account||null)}
 useEffect(()=>{refresh()},[]);
 async function addAccount(){setLoading(true);await fetch("/api/accounts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({platform:"instagram"})});setMessage("تم إنشاء حساب تجريبي فارغ فقط");setLoading(false);refresh()}
 async function addWorker(){setLoading(true);await fetch("/api/workers",{method:"POST"});setMessage("Worker 01 جاهز");setLoading(false);refresh()}
 async function connectInstagram(){if(!username.trim()||!accountId.trim())return;setLoading(true);const r=await fetch("/api/instagram",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,accountId})});setMessage(r.ok?"تم ربط حساب Instagram بالـWorker 01":"فشل الربط");setLoading(false);refresh()}
 async function disconnectInstagram(){setLoading(true);await fetch("/api/instagram",{method:"DELETE"});setMessage("تم فصل الحساب");setLoading(false);refresh()}
 async function createJob(){if(!url.trim())return;setLoading(true);const r=await fetch("/api/jobs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({targetUrl:url,action,count:Number(count)})});setMessage(r.ok?"تم إنشاء Job في الـQueue":"حصل خطأ في إنشاء الـJob");setLoading(false);refresh()}
 async function runJob(id){setLoading(true);const r=await fetch("/api/jobs/"+id+"/run",{method:"POST"});setMessage(r.ok?"تم تشغيل الـJob داخل الـLab":"تعذر تشغيل الـJob");setLoading(false);refresh()}
 return <main dir="rtl" style={{maxWidth:1100,margin:"30px auto",padding:20,fontFamily:"Arial,sans-serif"}}>
 <header style={{marginBottom:24}}><h1 style={{marginBottom:6}}>View Test Lab</h1><p style={{color:"#667085"}}>Control Center — Account Pool / Workers / Jobs / Logs</p></header>
 <section style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginBottom:24}}>
 {[[accounts.length,"Accounts"],[workers.filter(x=>x.status!=="offline").length,"Workers"],[jobs.length,"Jobs"],[jobs.filter(x=>x.status==="queued").length,"Queued"]].map(([n,l])=><div key={l} style={{background:"#fff",padding:20,borderRadius:14,boxShadow:"0 3px 16px #0000000d"}}><div style={{fontSize:28,fontWeight:700}}>{n}</div><div style={{color:"#667085"}}>{l}</div></div>)}
 </section>
 <section style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:18}}>
 <div style={{background:"#fff",padding:22,borderRadius:16}}><h2>Instagram Account / Worker</h2>{ig?.status==="connected"?<div style={{padding:12,background:"#eefbf3",borderRadius:10,marginBottom:12}}><b>@{ig.username}</b><br/><small>Account ID: {ig.accountId}<br/>Worker: {ig.workerId}<br/>Connected: {new Date(ig.connectedAt).toLocaleString()}</small><br/><button onClick={disconnectInstagram} disabled={loading} style={{marginTop:10,padding:"8px 12px",border:0,borderRadius:8}}>Disconnect</button></div>:<div style={{marginBottom:12}}><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Instagram username" style={{width:"100%",boxSizing:"border-box",padding:10,marginBottom:8}}/><input value={accountId} onChange={e=>setAccountId(e.target.value)} placeholder="Instagram account ID" style={{width:"100%",boxSizing:"border-box",padding:10,marginBottom:8}}/><button onClick={connectInstagram} disabled={loading||!username.trim()||!accountId.trim()} style={{padding:"9px 13px",border:0,borderRadius:8}}>Connect Account</button></div>}<h2>Accounts / Workers</h2><button onClick={addWorker} disabled={loading} style={{padding:"10px 14px",border:0,borderRadius:9}}>+ Add Worker</button><p style={{color:"#667085",fontSize:13}}>الحساب هنا بيانات ربط فقط؛ لا يتم حفظ كلمة مرور أو Session ولا تنفيذ تفاعل آلي على Instagram.</p>{accounts.map(a=><div key={a.id} style={{padding:"10px 0",borderTop:"1px solid #eee"}}><b>Account</b> · {a.status}</div>)}{workers.map(w=><div key={w.id} style={{padding:"10px 0",borderTop:"1px solid #eee"}}><b>Worker</b> · {w.status} · {w.id}</div>)}</div>
 <div style={{background:"#fff",padding:22,borderRadius:16}}><h2>New Job</h2><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="Target URL" style={{width:"100%",boxSizing:"border-box",padding:12,marginBottom:10}}/><div style={{display:"flex",gap:8}}><select value={action} onChange={e=>setAction(e.target.value)} style={{padding:10}}><option value="view">View</option><option value="like">Like</option><option value="comment">Comment</option></select><input type="number" min="1" max="20" value={count} onChange={e=>setCount(Math.min(20,Math.max(1,Number(e.target.value)||1)))} style={{width:80,padding:10}}/></div><button onClick={createJob} disabled={loading||!url.trim()} style={{marginTop:12,padding:"10px 16px",border:0,borderRadius:9}}>Create Job</button>{message&&<p>{message}</p>}</div>
 </section>
 <section style={{background:"#fff",padding:22,borderRadius:16,marginTop:18}}><h2>Jobs / Queue</h2>{jobs.length===0?<p style={{color:"#667085"}}>No jobs yet.</p>:jobs.map(j=><div key={j.id} style={{padding:"13px 0",borderTop:"1px solid #eee"}}><b>{j.action}</b> × {j.count} · <span>{j.status}</span>{j.status==="queued"&&<button onClick={()=>runJob(j.id)} disabled={loading} style={{marginRight:10,padding:"6px 10px",border:0,borderRadius:7}}>Run in Lab</button>}<br/><small>{j.targetUrl} · {new Date(j.createdAt).toLocaleString()}</small></div>)}</section>
 <section style={{background:"#fff",padding:22,borderRadius:16,marginTop:18}}><h2>Logs</h2>{logs.length===0?<p style={{color:"#667085"}}>No logs yet.</p>:logs.slice(0,20).map(l=><div key={l.id} style={{padding:"9px 0",borderTop:"1px solid #eee"}}><b>{l.type}</b> · {l.message}<br/><small>{new Date(l.createdAt).toLocaleString()}</small></div>)}</section>
 <section style={{background:"#fff4e5",padding:16,borderRadius:14,marginTop:18}}><b>Safety status:</b> Platform adapter is NO-OP. Jobs only move through the synthetic Lab lifecycle; no Instagram views, likes, comments, follows, or other interactions are executed.</section>
 </main>
}